services:
  fileservice:
    image: ghcr.io/sogno-platform/pgm-service/fileservice:main
    build:
      context: test/fileservice
    volumes:
      - ./data:/data
    environment:
      DATA_DIR: "/data"
      BASE_URL: "http://fileservice:8080/"
    ports:
      - 8080:8080
  worker:
    image: ghcr.io/sogno-platform/pgm-service:main
    build:
      context: . 
    environment:
      FILESERVICE_URL: fileservice
    ports:
      - 80:80
